src/AppBundle/Entity/Pages.php
<?php

namespace AppBundle\Entity;

use AppBundle\Model\MainObjectabeleInterface;
use AppBundle\Traits\MainObject;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;


/**
 * Pages
 *
 * @ORM\Table(name="pages")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\PagesRepository")
 */
class Pages implements MainObjectabeleInterface
{
    use MainObject;
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var string
     *
     * @Gedmo\Slug(fields={"name"})
     * @ORM\Column(name="slug", type="string", length=255, unique=true)
     */
    private $slug;

    /**
     * @var
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created;

    /**
     * @var
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated;

    public function __toString()
    {
        return $this->id ? $this->getName() : 'New Page';
        // TODO: Implement __toString() method.
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Pages
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set created
     *
     * @param \DateTime $created
     *
     * @return $this
     */
    public function setCreated($created)
    {
        $this->created = $created;

        return $this;
    }

    /**
     * Get created
     *
     * @return \DateTime
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Set updated
     *
     * @param \DateTime $updated
     *
     * @return $this
     */
    public function setUpdated($updated)
    {
        $this->updated = $updated;

        return $this;
    }

    /**
     * Get updated
     *
     * @return \DateTime
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * Get fileName
     *
     * @return string
     */
    public function getClassName()
    {
        return get_class($this);
    }

    /**
     * @return string
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * @param string $slug
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;
    }
}

src/AppBundle/Form/BooleanType.php
<?php

namespace AppBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BooleanType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('value')->add('title')->add('slug')->add('sortOrdering')->add('created')->add('updated')->add('formType');
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\Boolean'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'appbundle_boolean';
    }


}

src/AppBundle/Form/ContactType.php
<?php

namespace AppBundle\Form;

use AppBundle\Entity\Settings;
use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ContactType extends AbstractType
{

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {


        $builder
            ->add('name', 'text', ['label'=>false, 'required'=>true, 'attr'=>['placeholder'=>'Name', 'minlength'=>5]])
            ->add('email', 'email', ['label'=>false, 'required'=>true, 'attr'=>['placeholder'=>'Email']])
            ->add('phone', 'text', ['label'=>false, 'required'=>false, 'attr'=>['placeholder'=>'Phone']])
            ->add('message', 'textarea', ['label'=>false, 'required'=>true, 'attr'=>['placeholder'=>'Message', 'minlength'=>20]])
//            ->add('send', 'submit', ['attr'=>['class'=>'btn btn1']])
            ;


    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([]);
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'app_bundle_contact';
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'app_bundle_contact';
    }

}

src/AppBundle/Form/DateType.php
<?php

namespace AppBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DateType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('value')->add('title')->add('slug')->add('sortOrdering')->add('created')->add('updated')->add('formType');
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\Date'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'appbundle_date';
    }


}

src/AppBundle/Form/DocumentType.php
<?php

namespace AppBundle\Form;

use AppBundle\Entity\Settings;
use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DocumentType extends AbstractType
{

    private $container;
    private $em;

    public function __construct(Container $container)
    {
        $this->container = $container;
        $this->em = $container->get('doctrine')->getManager();
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        $data = $options['data'];

        $settings = $this->em->getRepository('AppBundle:Settings')->findFrom($data->getId(), $options['data_class']);

        if(!is_null($settings)){
            foreach ($settings as $setting){
            $data->addFromSettings($setting);
        }
            $builder
                ->add('fromSettings', 'app_bundle_parameters', ['from_id'=>$data->getId(), 'from_class_name'=> $options['data_class'],
                    'data'=>$settings, 'mapped' => false,]);
        }



        $builder
            ->add('title', 'hidden')
            ->add('slug', 'hidden')
            ->add('sortOrdering', 'hidden')
            ->add('created')
            ->add('updated')
            ->add('formType', 'hidden');
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\Document',
            'form_type_text'=>null
            /*'object_id'=>null,
            'object_name'=>null,*/

        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'app_bundle_document';
    }


    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'app_bundle_document';
    }


}

src/AppBundle/Form/DocumentsListType.php
<?php

namespace AppBundle\Form;

use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DocumentsListType extends AbstractType
{
    private $container;
    private $em;

    public function __construct(Container $container)
    {
        $this->container = $container;
        $this->em = $container->get('doctrine')->getManager();
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $data = $options['data'];

        $settings = $this->em->getRepository('AppBundle:Settings')->findFrom($data->getId(), $options['data_class']);

        if(!is_null($settings)){
            foreach ($settings as $setting){
                $data->addFromSettings($setting);
            }
            $builder
                ->add('fromSettings', 'app_bundle_parameters', ['from_id'=>$data->getId(), 'from_class_name'=> $options['data_class'],
                    'data'=>$settings, 'mapped' => false,]);
        }



        $builder
            ->add('title', 'hidden')
            ->add('slug', 'hidden')
            ->add('sortOrdering', 'hidden')
            ->add('created')
            ->add('updated')
            ->add('formType', 'hidden');
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\DocumentsList',
            'form_type_text'=>null
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'app_bundle_documents_list';
    }


    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'app_bundle_documents_list';
    }


}

src/AppBundle/Form/FileFormType.php
<?php
namespace AppBundle\Form;
use AppBundle\Entity\MenuItom;
use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class FileFormType extends AbstractType
{
    /**
     * @return null|string|\Symfony\Component\Form\FormTypeInterface
     */
    public function getParent()
    {
        return 'file';
    }
    /**
     * @return string
     */
    public function getName()
    {
        return 'file_form_type';
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults( array(
            'belongs_to'=>false
        ));
    }
}

src/AppBundle/Form/FileType.php
<?php

namespace AppBundle\Form;

use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FileType extends AbstractType
{
    private $contaiiner;

    public function __construct(Container $container)
    {
        $this->contaiiner = $container;
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        $builder
            ->add('state', null, ['label'=>'Active'])
            ->add('file', $options['form_type_text'])
            ->add('fileOriginalName', 'hidden')
            ->add('fileName', 'hidden')
            ->add('title', 'hidden')
            ->add('slug', 'hidden')
            ->add('sortOrdering', 'hidden')
            ->add('created')
            ->add('updated')
            ->add('formType', 'hidden')
            ->addModelTransformer(new CallbackTransformer(

                function ($tagsAsArray) {
                    // transform the array to a string
                    return $tagsAsArray;
                },
                function ($beforeParsist) {
//                    if(!is_null($beforeParsist->file)){
                        $beforeParsist->uploadFile();
//                    }

                    // transform the string back to an array
                    return $beforeParsist;
                }
            ))
        ;
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\File',
            'form_type_text'=>null
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'app_bundle_file';
    }

    public function getName()
    {
        return 'app_bundle_file';
    }

}

src/AppBundle/Form/IconType.php
<?php
namespace AppBundle\Form;
use AppBundle\Entity\MenuItom;
use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class IconType extends AbstractType
{
    /**
     * @return null|string|\Symfony\Component\Form\FormTypeInterface
     */
    public function getParent()
    {
        return 'file';
    }
    /**
     * @return string
     */
    public function getName()
    {
        return 'icon_type';
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults( array(
            'belongs_to'=>false
        ));
    }
}

src/AppBundle/Form/RegistrationType.php
<?php

namespace AppBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RegistrationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('firstName', 'text', array('required'=>true, 'attr'=>array('class'=>'form-control')))
            ->add('lastName','text',array('required'=>true, 'attr'=>array('class'=>'form-control')))
;
    }

    public function getParent()
    {
        return 'FOS\UserBundle\Form\Type\RegistrationFormType';

        // Or for Symfony < 2.8
        // return 'fos_user_registration';
    }

    public function getBlockPrefix()
    {
        return 'app_user_registration';
    }

    // For Symfony 2.x
    public function getName()
    {
        return $this->getBlockPrefix();
    }
}

src/AppBundle/Form/TextType.php
<?php

namespace AppBundle\Form;

use AppBundle\Entity\Settings;
use AppBundle\Entity\Text;
use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TextType extends AbstractType
{
    private $container;
    private $em;

    public function __construct(Container $container)
    {
        $this->container= $container;
        $this->em = $container->get('doctrine')->getManager();
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $formType = $options['form_type_text'];

        $textOptions = ['label'=>false, 'required' => false];
        if($formType == 'ckeditor'){
            $textOptions = array_merge($textOptions, [
                'trim' => true,
                'auto_inline'=>true,
                'config' => array(
                    'uiColor' => '#ffffff',
                    'required'=>true)]) ;
        }

        $builder->add('value', $formType, $textOptions
                    )
            ->add('title', 'hidden')
            ->add('slug', 'hidden')
            ->add('sortOrdering', 'hidden')
            ->add('formType', 'hidden')
            ->addModelTransformer(new CallbackTransformer(

                function ($tagsAsArray) {
                    // transform the array to a string
                    return $tagsAsArray;
                },
                function ($beforeParsist) {

                   /* dump($beforeParsist);

                    $log = $this->container->get('monolog.logger.process_error');

                    $message = $beforeParsist->getId() . '-' . $beforeParsist->getValue();
                    $log->addInfo("dataText : {$message}");

                    $this->em->persist($beforeParsist);
                    $this->em->flush();*/

                    // transform the string back to an array
                    return $beforeParsist;
                }
            ))
        ;
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\Text',
            'form_type_text'=>null
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'app_bundle_text';
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'app_bundle_text';
    }

}

src/AppBundle/Resources/views/Form/app_bundle_contact.html.twig
{% block app_bundle_contact_widget %}
    
    {{ form_widget(form) }}
    
{% endblock app_bundle_contact_widget %}

src/AppBundle/Resources/views/Form/app_bundle_document.htm.twig
{% block app_bundle_document_widget %}
    <div class="row">
        <div class="col-md-12">
            {{ form_widget(form.title) }}
            {{ form_widget(form.slug) }}
            {{ form_widget(form.sortOrdering) }}
            <div class="hidden">
                {{ form_widget(form.created) }}
                {{ form_widget(form.updated) }}
            </div>
            {% if form.fromSettings is defined %}
                {{ form_widget(form.fromSettings) }}

            {% else %}
                <a href="{{ path('admin_app_document_edit', {'id':form.vars.value.id}) }}">add settings</a>
            {% endif %}
            {% if is_granted('ROLE_SONATA_ADMIN') %}<a href="{{ path('admin_app_document_edit', {'id':form.vars.value.id}) }}">add Item in {{ form.vars.value.title }}</a>{% endif %}
            {{ form_widget(form.formType) }}
        </div>
    </div>
{% endblock app_bundle_document_widget %}

src/AppBundle/Resources/views/Form/app_bundle_documents_list.htm.twig
{% block app_bundle_documents_list_widget %}
    <div class="row">
        <div class="col-md-12">
            {{ form_widget(form.title) }}
            {{ form_widget(form.slug) }}
            {{ form_widget(form.sortOrdering) }}
            <div class="hidden">
                {{ form_widget(form.created) }}
                {{ form_widget(form.updated) }}
            </div>
            {% if form.fromSettings is defined %}
                {{ form_widget(form.fromSettings) }}

            {% else %}
                <a href="{{ path('admin_app_document_edit', {'id':form.vars.value.id}) }}">add settings</a>
            {% endif %}
            {% if is_granted('ROLE_SONATA_ADMIN') %}<a href="{{ path('admin_app_documentslist_edit', {'id':form.vars.value.id}) }}">Add documents in {{ form.vars.value.title }}</a>{% endif %}
            {{ form_widget(form.formType) }}
        </div>
    </div>
{% endblock app_bundle_documents_list_widget %}

src/AppBundle/Resources/views/Form/app_bundle_file.html.twig
{% block app_bundle_file_widget %}
    <div class="row">

            <div class="col-md-2">
                {{ form_widget(form.state) }}
            </div><div class="col-md-8">
                {{ form_widget(form.file) }}
            </div>
            <div class="hidden">
                {{ form_widget(form.fileOriginalName) }}
                {{ form_widget(form.fileName) }}
                {{ form_widget(form.title) }}
                {{ form_widget(form.slug) }}
                {{ form_widget(form.sortOrdering) }}
                {{ form_widget(form.formType) }}
                {{ form_widget(form.created) }}
                {{ form_widget(form.updated) }}
            </div>
    </div>
{% endblock app_bundle_file_widget %}

src/AppBundle/Resources/views/Form/app_bundle_parameters.html.twig
{% block app_bundle_parameters_widget %}
    <div class="row">
        <div class="col-md-12">
           {{ form_widget(form) }}
        </div>
    </div>
{% endblock app_bundle_parameters_widget %}

src/AppBundle/Resources/views/Form/app_bundle_settings.html.twig
{% block app_bundle_settings_widget %}
    <div class="row ui-state-default">

        <div class="col-md-4 col-sm-6 col-xs-6">
            {{ form_widget(form.name) }}
            {{ form_widget(form.fromClassName) }}
            {{ form_widget(form.toClassName) }}
            {{ form_widget(form.fromId) }}
            {{ form_widget(form.toId) }}
            {{ form_widget(form.position) }}
        </div>
        <div class="col-md-4 col-sm-6 col-xs-6">
            {{ form_widget(form.toClassType) }}
        </div>
        <div class="col-md-3 col-sm-4 col-xs-8">
            {{ form_widget(form.inEnabled) }}
        </div>
        <div class="col-md-1 col-sm-2 col-xs-4">
            <div class="form-group">
                <a class="btn btn-info btn-xs" type="clone" href="{{ path('rest_get_admin_clone', {'objectType': form.toClassType.vars.value|number_format , 'objectId': form.toId.vars.value|number_format }) }}">
                    <i class="fa fa-files-o" aria-hidden="true"></i>
                </a>
            </div>

        </div>

    </div>

{% endblock app_bundle_settings_widget %}

src/AppBundle/Resources/views/Form/app_bundle_text.html.twig
{% block app_bundle_text_widget %}
    <div class="row">
        <div class="col-md-12">
            {{ form_widget(form) }}
        </div>
    </div>
{% endblock app_bundle_text_widget %}

src/AppBundle/Resources/views/Form/file_form_type.html.twig
{% block file_form_type_widget %}
    {% set object = form.parent.vars.value %}
    {% set filename = object.filename %}
    {% if filename %}
            <input type="hidden" value="{{ object.fileOriginalName }}">
        <a class="" target="_blank" href="{{ object.downloadLink }}"><i class="fa fa-file-archive-o" aria-hidden="true"></i>&nbsp;{{ object.fileOriginalName }}</a>
        <a href="{{ path('remove_image', {'filename' : filename, 'object' : object.className  }) }}">
            <span class="glyphicon glyphicon-remove"></span></a>
    {% else  %}
        {{ form_widget(form) }}
    {% endif %}

{% endblock file_form_type_widget %}

src/AppBundle/Resources/views/Form/icon.html.twig
{% block icon_type_widget %}

    {% set object = form.parent.vars.value %}
    {% set filename = object.filename %}
    {% if filename %}
        <a href="#" data-toggle="modal" data-target="#imagemodal" class="icon-type-widget">
            <input type="hidden" value="{{ object.fileOriginalName }}">
            <img class="img-responsive form-image" src="{{ object.downloadLink }}">
        </a>
        <a href="{{ path('remove_image', {'filename' : filename, 'object' : object.className  }) }}">
            <span class="glyphicon glyphicon-remove"></span></a>
    {% else  %}
        {{ form_widget(form) }}
    {% endif %}

{% endblock icon_type_widget %}